#!/usr/bin/env python3
"""build_demo.py — generate two editable Office deliverables, then validate
and render them with OfficeCLI.

The data here is illustrative (a fictional "Riverside County Council" alt-
provision pack), so the kit runs standalone with nothing confidential in it.
Swap the DocSpec and the tracker rows for your own and you have a repeatable
"agent returns an editable file" pipeline.

Division of labour, and the whole point of the ship:
  * python-docx / openpyxl  -> GENERATE the file from structured data
  * OfficeCLI               -> VALIDATE (OpenXML schema), inspect, render

Run:  python3 build_demo.py            (generation only, no OfficeCLI needed)
      OFFICECLI=./officecli python3 build_demo.py   (also validate + render)
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from office_pack import DocSpec, Section, Table, build_docx, build_tracker

OUT = Path(__file__).parent / "out"
OUT.mkdir(exist_ok=True)

# --- 1. the decision-pack .docx ---------------------------------------------
PACK = DocSpec(
    title="Alt-Provision Placement Pack",
    subtitle="A shared record for school exclusion and alternative placement.",
    prepared_for="Prepared for Riverside County Council, Inclusion Support (illustrative demo data).",
    footer=(
        "Generated by an agent as an editable Word file. Every number below is "
        "a live cell you can change before you send it on."
    ),
    sections=[
        Section(
            heading="1. The problem",
            body=[
                "Managing a permanent exclusion or an EHCP placement is one of the "
                "highest-cost duties an inclusion team carries, and most authorities "
                "still run it on email threads and loose spreadsheets. There is no "
                "shared record, no visible statutory clock, and no live picture of "
                "where there is capacity.",
                "The single point to take from this pack: the biggest hidden cost of "
                "a placement is transport, and it is locked in the moment you choose "
                "where a child goes.",
            ],
        ),
        Section(
            heading="2. Costs and savings",
            body=[
                "The licence is priced per placement case per year. The model below "
                "is set at the bottom of each published range by design, so it "
                "survives scrutiny rather than flattering the product.",
            ],
            table=Table(rows=[
                ["Line", "Basis", "Annual value"],
                ["Coordination time saved", "Half of manual admin removed", "£42,000"],
                ["Disputes avoided", "1 case in 20 kept out of formal complaint", "£28,000"],
                ["Placements nearer home", "1 in 20 on transport-cost visibility", "£54,000"],
                ["Licence cost", "Per-case, illustrative caseload", "-£30,000"],
                ["Net saving", "", "£94,000"],
            ]),
        ),
        Section(
            heading="3. Why editable matters",
            body=[
                "This document was produced by an agent as a .docx, not a PDF. An "
                "officer can change the caseload, correct a figure, or drop a "
                "paragraph and forward it, without coming back to us. That is the "
                "difference between a document and a photograph of a document.",
            ],
        ),
    ],
)

# --- 2. the placements / transport-cost tracker .xlsx -----------------------
TRACKER_HEADERS = [
    "Case ref", "Pupil (initials)", "Provision", "Miles from home",
    "Return trips/day", "School days/yr", "Cost per mile (£)",
    "Annual transport (£)",
]
# Columns 3,4,5,6 feed the formula in column 7 (0-based). {r} = spreadsheet row.
TRACKER_ROWS = [
    ["AP-1001", "J.M.", "Chiltern Futures",   5, 2, 190, 1.20, None],
    ["AP-1002", "S.K.", "Riverside PRU",      12, 2, 190, 1.20, None],
    ["AP-1003", "T.O.", "Oakwood AP",         24, 2, 190, 1.20, None],
    ["AP-1004", "L.B.", "Chiltern Futures",    8, 2, 190, 1.20, None],
    ["AP-1005", "R.P.", "Meadow Independent",  31, 2, 190, 1.20, None],
]
# Annual transport = miles * trips * days * cost-per-mile. Live, editable in Excel.
FORMULA_COLS = {7: "=D{r}*E{r}*F{r}*G{r}"}
TOTAL_COLS = [7]


def _officecli(oc: str, *args: str) -> dict:
    res = subprocess.run([oc, *args, "--json"], capture_output=True, text=True)
    try:
        return json.loads(res.stdout or "{}")
    except json.JSONDecodeError:
        return {"success": False, "raw": res.stdout, "err": res.stderr}


def main() -> None:
    docx_path = str(OUT / "alt-provision-placement-pack.docx")
    xlsx_path = str(OUT / "placements-transport-tracker.xlsx")

    build_docx(PACK, docx_path)
    print("WROTE", docx_path)
    build_tracker(
        TRACKER_HEADERS, TRACKER_ROWS, xlsx_path,
        sheet_title="Placements",
        formula_cols=FORMULA_COLS, total_cols=TOTAL_COLS,
    )
    print("WROTE", xlsx_path)

    oc = os.environ.get("OFFICECLI")
    if not oc or not Path(oc).exists():
        print("\n(OFFICECLI not set — skipping validate/render. "
              "Set OFFICECLI=/path/to/officecli to enable.)")
        return

    for path in (docx_path, xlsx_path):
        # We wrote these to disk directly with python-docx/openpyxl. If OfficeCLI
        # still holds a resident for the path from an earlier run, its reads serve
        # the stale in-memory copy — so close it first, then validate the file.
        _officecli(oc, "close", path)
        v = _officecli(oc, "validate", path)
        ok = v.get("success")
        print(f"VALIDATE {Path(path).name}: "
              f"{'PASS' if ok else 'FAIL'} — {v.get('data') or v.get('error')}")
        if not ok:
            sys.exit(1)

    # Render an HTML preview of the docx via OfficeCLI's own engine
    html = subprocess.run([oc, "view", docx_path, "html"],
                          capture_output=True, text=True).stdout
    preview = OUT / "pack-preview.html"
    preview.write_text(html)
    print("WROTE", preview, f"({len(html)} bytes)")


if __name__ == "__main__":
    main()
