#!/usr/bin/env python3
"""
egress_guard — default-deny egress for the fleet, the safe way.

A default-deny firewall on a live box running the fleet is one wrong line away
from cutting Telegram, Supabase, the model APIs and git all at once. So this does
the safe 90% and stops short of the dangerous 10%:

  audit    sweep the agent code for every outbound host and classify each against
           the allowlist (ALLOWED / OFF-LIST / DENY-FLAGGED). A static dry-run:
           it tells you what the fleet reaches without touching the network.
  check    is a single host allowed by policy.
  gen-nft  emit a default-deny nftables ruleset (loopback + established + DNS +
           the allowlisted hosts, everything else dropped), resolved to current
           IPs, with a NOT-ARMED header. It prints a ruleset; it never applies one.

Arming enforcement is a human decision, on purpose. See the notes gen-nft prints.

Dependency-free: stdlib only.
"""

import argparse
import os
import re
import socket
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import allowlist as AL  # noqa: E402

FLEET_DIRS = [
    "/home/workloft/ruby", "/home/workloft/gary", "/home/workloft/walt",
    "/home/workloft/vera", "/home/workloft/audit", "/home/workloft/typefully",
    "/home/workloft/weekly-digest", "/home/workloft/.claude/hooks",
    "/home/workloft/observability",
]
HOST_RE = re.compile(r"https?://([a-zA-Z0-9._-]+\.[a-z]{2,})")
IGNORE_HOSTS = {"schema.org", "www.w3.org", "localhost"}
CODE_EXT = (".py", ".sh", ".js", ".ts")


def discover_hosts(paths):
    hosts = {}
    for root in paths:
        for dp, _dn, fns in os.walk(root):
            if "/.git" in dp or "__pycache__" in dp or "/node_modules" in dp:
                continue
            for fn in fns:
                if not fn.endswith(CODE_EXT):
                    continue
                fp = os.path.join(dp, fn)
                try:
                    text = open(fp, errors="ignore").read()
                except Exception:
                    continue
                for m in HOST_RE.findall(text):
                    h = m.lower().rstrip(".")
                    if h in IGNORE_HOSTS or h.startswith("127."):
                        continue
                    hosts.setdefault(h, set()).add(fp.replace("/home/workloft/", ""))
    return hosts


def cmd_audit(a):
    hosts = discover_hosts(a.paths or FLEET_DIRS)
    allowed, offlist, denied = [], [], []
    for h in sorted(hosts):
        base_deny = next((d for d in AL.DENYLIST_NOTES if h == d or h.endswith("." + d)), None)
        if base_deny:
            denied.append((h, base_deny))
        elif AL.is_allowed(h):
            allowed.append(h)
        else:
            offlist.append(h)
    print(f"egress audit: {len(hosts)} distinct outbound hosts in the fleet code\n")
    print(f"ALLOWED ({len(allowed)}): on policy")
    for h in allowed:
        print(f"  ok    {h}")
    if denied:
        print(f"\nDENY-FLAGGED ({len(denied)}): reached in code but explicitly denied")
        for h, base in denied:
            print(f"  DENY  {h}  ({AL.DENYLIST_NOTES[base]})")
            for src in sorted(hosts[h])[:3]:
                print(f"          seen in {src}")
    if offlist:
        print(f"\nOFF-LIST ({len(offlist)}): reached but NOT on the allowlist, decide each")
        for h in offlist:
            print(f"  ??    {h}")
            for src in sorted(hosts[h])[:3]:
                print(f"          seen in {src}")
    print("\nverdict:", "CLEAN (every host is a conscious decision)"
          if not offlist and not denied else
          f"{len(offlist)} off-list + {len(denied)} deny-flagged to resolve before enforce")
    return 0 if not offlist and not denied else 1


def cmd_check(a):
    ok = AL.is_allowed(a.host)
    print(f"{a.host}: {'ALLOWED' if ok else 'NOT ALLOWED'}")
    return 0 if ok else 1


def _resolve(domain):
    ips = set()
    for fam in (socket.AF_INET,):
        try:
            for res in socket.getaddrinfo(domain, 443, fam, socket.SOCK_STREAM):
                ips.add(res[4][0])
        except Exception:
            pass
    return sorted(ips)


def cmd_gen_nft(a):
    lines = [
        "#!/usr/sbin/nft -f",
        "# ===================================================================",
        "# Workloft fleet egress: DEFAULT-DENY ruleset.  *** NOT ARMED ***",
        "# Generated by egress_guard.py. Review, then a human applies it with:",
        "#     sudo nft -f this-file.nft",
        "# Undo with:  sudo nft flush ruleset   (or reboot if unsaved).",
        "#",
        "# HONEST LIMITS: this allowlists by RESOLVED IP at generation time.",
        "# CDN IPs drift and are shared, so this is a coarse backstop, not the",
        "# real control. For robust domain allowlisting, front outbound traffic",
        "# with an egress PROXY that allowlists by TLS SNI / Host header.",
        "# Re-run this generator on a schedule if you do arm the L3 version.",
        "# ===================================================================",
        "",
        "table inet egress {",
        "  chain output {",
        "    type filter hook output priority 0; policy drop;",
        "",
        "    ct state established,related accept",
        "    oif \"lo\" accept",
        "    udp dport 53 accept",
        "    tcp dport 53 accept",
        "",
    ]
    total_ips = 0
    for cat, entries in AL.ALLOWLIST.items():
        lines.append(f"    # --- {cat} ---")
        for domain, purpose in entries:
            ips = _resolve(domain)
            total_ips += len(ips)
            if not ips:
                lines.append(f"    # {domain}: no A record resolved at gen time ({purpose})")
                continue
            joined = ", ".join(ips)
            lines.append(f"    ip daddr {{ {joined} }} tcp dport {{ 80, 443 }} accept  # {domain} ({purpose})")
        lines.append("")
    lines += [
        "    # everything else is dropped by policy above",
        '    log prefix "egress-drop " level warn',
        "  }",
        "}",
        "",
    ]
    text = "\n".join(lines)
    out = a.out
    if out:
        with open(out, "w") as f:
            f.write(text)
        print(f"wrote NOT-ARMED ruleset ({total_ips} resolved IPs) -> {out}")
        print("review it, then a human arms it with: sudo nft -f " + out)
    else:
        print(text)
    return 0


def main():
    ap = argparse.ArgumentParser(prog="egress_guard")
    sub = ap.add_subparsers(dest="cmd", required=True)
    pa = sub.add_parser("audit"); pa.add_argument("paths", nargs="*")
    pa.set_defaults(func=cmd_audit)
    pc = sub.add_parser("check"); pc.add_argument("host")
    pc.set_defaults(func=cmd_check)
    pg = sub.add_parser("gen-nft"); pg.add_argument("--out", default=None)
    pg.set_defaults(func=cmd_gen_nft)
    a = ap.parse_args()
    sys.exit(a.func(a))


if __name__ == "__main__":
    main()
